---
# External roles from Ansible Galaxy
roles:
  - name: geerlingguy.java
    version: 2.3.0
  
  - name: geerlingguy.jenkins
    version: 5.3.0
  
  - name: geerlingguy.docker
    version: 7.4.1

# Collections
collections:
  - name: ansible.posix
    version: "1.5.4"
