---
# Main playbook for CI/CD environment
- hosts: jenkins
  become: yes
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - jenkins-config

- hosts: jenkins_agents
  become: yes
  roles:
    - geerlingguy.java
    - geerlingguy.docker
    - jenkins-agent

- hosts: webapp
  become: yes
  roles:
    - webapp
